### ISSUE TITLE
IFFExplorer and SimSynchronizer could not be loaded

### ISSUE THREAD

**Issue by ZackCDLVI** [francot514/SimsNhood#1]
Is this needed?

> C:\Users\Zack\Documents\GitHub\SimsNhood\IFFExplorer\IFFExplorer.csproj : error  : The project file could not be loaded. Could not find a part of the path 'C:\Users\Zack\Documents\GitHub\SimsNhood\IFFExplorer\IFFExplorer.csproj'.  C:\Users\Zack\Documents\GitHub\SimsNhood\IFFExplorer\IFFExplorer.csproj

> C:\Users\Zack\Documents\GitHub\SimsNhood\SimsSynchronizer\SimSynchronizer.csproj : error  : The project file could not be loaded. Could not find a part of the path 'C:\Users\Zack\Documents\GitHub\SimsNhood\SimsSynchronizer\SimSynchronizer.csproj'.  C:\Users\Zack\Documents\GitHub\SimsNhood\SimsSynchronizer\SimSynchronizer.csproj

**Comment by francot514** [comment]
Not really, just was testing and forgot to delete, this is not a necessary issue

**Comment by ZackCDLVI** [comment]
Issue tracker is used for other things then issues. Like sugguestions and questions.
